const mongoose = require('mongoose');
const Phrase = require('../models/Phrase');
require('dotenv').config();

// Extended seed data based on the TypeScript frontend implementation
const phraseData = [
  // Courtesy phrases
  { original: 'please', simplified: '', category: 'courtesy' },
  { original: 'thank you', simplified: '', category: 'courtesy' },
  { original: 'thanks', simplified: '', category: 'courtesy' },
  { original: 'i would like you to', simplified: '', category: 'courtesy' },
  { original: 'could you', simplified: '', category: 'courtesy' },
  { original: 'would you', simplified: '', category: 'courtesy' },
  { original: 'kindly', simplified: '', category: 'courtesy' },
  { original: "if you don't mind", simplified: '', category: 'courtesy' },
  { original: 'if possible', simplified: '', category: 'courtesy' },
  { original: 'i was wondering if', simplified: '', category: 'courtesy' },
  { original: 'i would appreciate if', simplified: '', category: 'courtesy' },
  { original: 'it would be great if', simplified: '', category: 'courtesy' },
  
  // Contractions
  { original: 'i am', simplified: "I'm", category: 'contraction' },
  { original: 'you are', simplified: "you're", category: 'contraction' },
  { original: 'we are', simplified: "we're", category: 'contraction' },
  { original: 'they are', simplified: "they're", category: 'contraction' },
  { original: 'it is', simplified: "it's", category: 'contraction' },
  { original: 'that is', simplified: "that's", category: 'contraction' },
  { original: 'who is', simplified: "who's", category: 'contraction' },
  { original: 'what is', simplified: "what's", category: 'contraction' },
  { original: 'where is', simplified: "where's", category: 'contraction' },
  { original: 'when is', simplified: "when's", category: 'contraction' },
  { original: 'why is', simplified: "why's", category: 'contraction' },
  { original: 'how is', simplified: "how's", category: 'contraction' },
  { original: 'i have', simplified: "I've", category: 'contraction' },
  { original: 'you have', simplified: "you've", category: 'contraction' },
  { original: 'we have', simplified: "we've", category: 'contraction' },
  { original: 'they have', simplified: "they've", category: 'contraction' },
  { original: 'i would', simplified: "I'd", category: 'contraction' },
  { original: 'you would', simplified: "you'd", category: 'contraction' },
  { original: 'he would', simplified: "he'd", category: 'contraction' },
  { original: 'she would', simplified: "she'd", category: 'contraction' },
  { original: 'it would', simplified: "it'd", category: 'contraction' },
  { original: 'we would', simplified: "we'd", category: 'contraction' },
  { original: 'they would', simplified: "they'd", category: 'contraction' },
  { original: 'i will', simplified: "I'll", category: 'contraction' },
  { original: 'you will', simplified: "you'll", category: 'contraction' },
  { original: 'he will', simplified: "he'll", category: 'contraction' },
  { original: 'she will', simplified: "she'll", category: 'contraction' },
  { original: 'it will', simplified: "it'll", category: 'contraction' },
  { original: 'we will', simplified: "we'll", category: 'contraction' },
  { original: 'they will', simplified: "they'll", category: 'contraction' },
  { original: 'cannot', simplified: "can't", category: 'contraction' },
  { original: 'do not', simplified: "don't", category: 'contraction' },
  { original: 'does not', simplified: "doesn't", category: 'contraction' },
  { original: 'did not', simplified: "didn't", category: 'contraction' },
  { original: 'has not', simplified: "hasn't", category: 'contraction' },
  { original: 'have not', simplified: "haven't", category: 'contraction' },
  { original: 'had not', simplified: "hadn't", category: 'contraction' },
  { original: 'is not', simplified: "isn't", category: 'contraction' },
  { original: 'are not', simplified: "aren't", category: 'contraction' },
  { original: 'was not', simplified: "wasn't", category: 'contraction' },
  { original: 'were not', simplified: "weren't", category: 'contraction' },
  { original: 'should not', simplified: "shouldn't", category: 'contraction' },
  { original: 'would not', simplified: "wouldn't", category: 'contraction' },
  { original: 'could not', simplified: "couldn't", category: 'contraction' },
  { original: 'will not', simplified: "won't", category: 'contraction' },
  { original: 'must not', simplified: "mustn't", category: 'contraction' },
  
  // Verbose phrases
  { original: 'in order to', simplified: 'to', category: 'verbose' },
  { original: 'for the purpose of', simplified: 'for', category: 'verbose' },
  { original: 'due to the fact that', simplified: 'because', category: 'verbose' },
  { original: 'in spite of the fact that', simplified: 'although', category: 'verbose' },
  { original: 'with regard to', simplified: 'about', category: 'verbose' },
  { original: 'in relation to', simplified: 'about', category: 'verbose' },
  { original: 'with reference to', simplified: 'about', category: 'verbose' },
  { original: 'in the event that', simplified: 'if', category: 'verbose' },
  { original: 'under the circumstances that', simplified: 'if', category: 'verbose' },
  { original: 'in the near future', simplified: 'soon', category: 'verbose' },
  { original: 'at this point in time', simplified: 'now', category: 'verbose' },
  { original: 'at the present time', simplified: 'now', category: 'verbose' },
  { original: 'it is important to note that', simplified: '', category: 'verbose' },
  { original: 'it should be noted that', simplified: '', category: 'verbose' },
  { original: 'it is worth noting that', simplified: '', category: 'verbose' },
  { original: 'as a matter of fact', simplified: 'actually', category: 'verbose' },
  { original: 'in my opinion', simplified: '', category: 'verbose' },
  { original: 'i think that', simplified: '', category: 'verbose' },
  { original: 'i believe that', simplified: '', category: 'verbose' },
  { original: 'for the most part', simplified: 'mostly', category: 'verbose' },
  { original: 'a large number of', simplified: 'many', category: 'verbose' },
  { original: 'a majority of', simplified: 'most', category: 'verbose' },
  { original: 'a significant number of', simplified: 'many', category: 'verbose' },
  { original: 'on the grounds that', simplified: 'because', category: 'verbose' },
  { original: 'in light of the fact that', simplified: 'because', category: 'verbose' },
  { original: 'on the basis of', simplified: 'from', category: 'verbose' },
  { original: 'with the exception of', simplified: 'except', category: 'verbose' },
  { original: 'in the process of', simplified: 'while', category: 'verbose' },
  { original: 'for the reason that', simplified: 'because', category: 'verbose' },
  { original: 'in the vicinity of', simplified: 'near', category: 'verbose' },
  { original: 'in close proximity to', simplified: 'near', category: 'verbose' },
  { original: 'until such time as', simplified: 'until', category: 'verbose' },
  { original: 'for the foreseeable future', simplified: 'indefinitely', category: 'verbose' },
  { original: 'it is possible that', simplified: 'possibly', category: 'verbose' },
  { original: 'there is a chance that', simplified: 'possibly', category: 'verbose' },
  { original: 'has the ability to', simplified: 'can', category: 'verbose' },
  { original: 'is able to', simplified: 'can', category: 'verbose' },
  { original: 'has the capacity to', simplified: 'can', category: 'verbose' },
  { original: 'in a timely manner', simplified: 'promptly', category: 'verbose' },
  { original: 'in an effort to', simplified: 'to', category: 'verbose' },
  { original: 'in an attempt to', simplified: 'to', category: 'verbose' },
  { original: 'at the conclusion of', simplified: 'after', category: 'verbose' },
  { original: 'in the aftermath of', simplified: 'after', category: 'verbose' },
  { original: 'during the course of', simplified: 'during', category: 'verbose' },
  { original: 'is indicative of', simplified: 'indicates', category: 'verbose' },
  { original: 'on a regular basis', simplified: 'regularly', category: 'verbose' },
  { original: 'on numerous occasions', simplified: 'often', category: 'verbose' },
  { original: 'take action to', simplified: '', category: 'verbose' },
  { original: 'make a decision to', simplified: 'decide to', category: 'verbose' },
  { original: 'come to a conclusion', simplified: 'conclude', category: 'verbose' },
  { original: 'draw a conclusion', simplified: 'conclude', category: 'verbose' },
  { original: 'reach a conclusion', simplified: 'conclude', category: 'verbose' },
  { original: 'make an adjustment to', simplified: 'adjust', category: 'verbose' },
  { original: 'provide an explanation for', simplified: 'explain', category: 'verbose' },
  { original: 'come to a realization', simplified: 'realize', category: 'verbose' },
  { original: 'take into consideration', simplified: 'consider', category: 'verbose' },
  { original: 'conduct an investigation', simplified: 'investigate', category: 'verbose' },
  { original: 'provide assistance to', simplified: 'help', category: 'verbose' },
  { original: 'give consideration to', simplified: 'consider', category: 'verbose' },
  { original: 'make a recommendation', simplified: 'recommend', category: 'verbose' },
  { original: 'provide a description of', simplified: 'describe', category: 'verbose' },
  { original: 'reach an agreement', simplified: 'agree', category: 'verbose' },
  { original: 'have a discussion about', simplified: 'discuss', category: 'verbose' },
  { original: 'make a statement', simplified: 'state', category: 'verbose' },
  { original: 'make an announcement', simplified: 'announce', category: 'verbose' },
  { original: 'have a tendency to', simplified: 'tend to', category: 'verbose' },
  { original: 'for all intents and purposes', simplified: 'essentially', category: 'verbose' },
  { original: 'at the end of the day', simplified: 'ultimately', category: 'verbose' },
  { original: 'when all is said and done', simplified: 'ultimately', category: 'verbose' },
  { original: 'needless to say', simplified: '', category: 'verbose' },
  { original: 'the fact of the matter is', simplified: '', category: 'verbose' },
  { original: 'as a general rule', simplified: 'generally', category: 'verbose' },
  { original: 'by the same token', simplified: 'similarly', category: 'verbose' },
  { original: 'the vast majority of', simplified: 'most', category: 'verbose' },
  { original: 'be that as it may', simplified: 'however', category: 'verbose' },
  { original: 'few and far between', simplified: 'rare', category: 'verbose' },
  { original: 'from time to time', simplified: 'occasionally', category: 'verbose' },
  { original: 'in this day and age', simplified: 'now', category: 'verbose' },
  { original: 'in due course', simplified: 'eventually', category: 'verbose' },
  { original: 'to all intents and purposes', simplified: 'effectively', category: 'verbose' },
  { original: 'the majority of', simplified: 'most', category: 'verbose' },
  { original: 'utilize', simplified: 'use', category: 'verbose' },
  { original: 'implement', simplified: 'use', category: 'verbose' },
  { original: 'sufficient', simplified: 'enough', category: 'verbose' },
  { original: 'numerous', simplified: 'many', category: 'verbose' },
  { original: 'commence', simplified: 'start', category: 'verbose' },
  { original: 'approximately', simplified: 'about', category: 'verbose' },
  { original: 'subsequently', simplified: 'then', category: 'verbose' },
  { original: 'nevertheless', simplified: 'still', category: 'verbose' },
  { original: 'consequently', simplified: 'so', category: 'verbose' },
  { original: 'acquire', simplified: 'get', category: 'verbose' },
  { original: 'demonstrate', simplified: 'show', category: 'verbose' },
  { original: 'endeavor', simplified: 'try', category: 'verbose' },
  { original: 'regarding', simplified: 'about', category: 'verbose' },
  { original: 'facilitate', simplified: 'help', category: 'verbose' },
  
  // Filler words
  { original: 'basically', simplified: '', category: 'filler' },
  { original: 'literally', simplified: '', category: 'filler' },
  { original: 'actually', simplified: '', category: 'filler' },
  { original: 'really', simplified: '', category: 'filler' },
  { original: 'frankly', simplified: '', category: 'filler' },
  { original: 'honestly', simplified: '', category: 'filler' },
  { original: 'quite', simplified: '', category: 'filler' },
  { original: 'just', simplified: '', category: 'filler' },
  { original: 'very', simplified: '', category: 'filler' },
  { original: 'somewhat', simplified: '', category: 'filler' },
  { original: 'essentially', simplified: '', category: 'filler' },
  { original: 'greatly', simplified: '', category: 'filler' },
  { original: 'much', simplified: '', category: 'filler' },
  { original: 'certainly', simplified: '', category: 'filler' },
  { original: 'definitely', simplified: '', category: 'filler' },
  { original: 'probably', simplified: '', category: 'filler' },
  { original: 'maybe', simplified: '', category: 'filler' },
  { original: 'perhaps', simplified: '', category: 'filler' },
  { original: 'possibly', simplified: '', category: 'filler' },
  { original: 'kind of', simplified: '', category: 'filler' },
  { original: 'sort of', simplified: '', category: 'filler' },
  { original: 'like', simplified: '', category: 'filler' },
  { original: 'you know', simplified: '', category: 'filler' },
  { original: 'I mean', simplified: '', category: 'filler' },
  { original: 'obviously', simplified: '', category: 'filler' },
  { original: 'simply put', simplified: '', category: 'filler' }
];

// Connect to MongoDB
const seedDatabase = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true
    });
    
    console.log('MongoDB connected...');
    
    // Delete existing phrases
    await Phrase.deleteMany();
    console.log('Existing phrases deleted...');
    
    // Insert new phrases
    await Phrase.insertMany(phraseData);
    console.log(`Successfully added ${phraseData.length} phrases to database!`);
    
    // Exit process
    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
};

seedDatabase();